baseURL = "http://chgallen.com"
languageCode = "en-us"
theme = "cocoa"
publishDir = "docs"

author = "Chad H.G. Allen"
title = "Chad H.G. Allen"

description = "Don't panic"

avatar = "img/profile.jpg"
