baseURL             = "http://chgallen.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-UK"
layoutdir           = "layouts"
publishdir          = "docs"
theme               = "cocoa"
author              = "Chad H.G. Allen"
title               = "Chad H.G. Allen"
pygmentsuseclasses  = true
#disqusshortname    = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
#googleAnalytics    = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "About"
weight                 = -140
identifier             = "about"
url                    = "/fixed/about/"

[[menu.main]]
name                   = "Blog"
weight                 = -130
identifier             = "blog"
url                    = "/blog/"


[[menu.main]]
name                   = "CV"
weight                 = -100
identifier             = "CV"
url                    = "docs/CV.pdf"

[[menu.main]]
name                   = "Publications"
weight                 = -110
identifier             = "pubs"
url                    = "/fixed/pubs/"

[params]
latestpostscount       = 0                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Chad H.G. Allen"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "2 Jan 2006"
dateformfull           = "Mon 2 Jan 2006 15:04:05 MST"
description            = "A lazily-made holding site."
email                  = "chad@chgallen.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/favicon.ico"
github                 = "//github.com/chgallen"
highlightjs            = true
instagram              = "//instagram.com/chgallen90"
lang                   = "en"
linkedin               = "//linkedin.com/in/chgallen"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "Under construction"                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/chgallen"
# mastodon             = "//example.com/@you"
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik				   = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id			   = 2                             # Id of your site in Piwik

avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

